# Reference to Helm repository
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: external-secrets
    namespace: flux-system
spec:
    interval: 1m
    url: https://charts.external-secrets.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    name: external-secrets
    namespace: flux-system
spec:
    interval: 10m
    ref:
        branch: main
    url: http://github.com/external-secrets/external-secrets

# resource "helm_release" "external-secrets" {
#  chart      = "external-secrets"
#  name       = "external-secrets"
#  repository = "https://charts.external-secrets.io"
#  namespace  = "external-secrets"
#
#  version = "0.9.17"
#
#  create_namespace = true
#  skip_crds = false
#
#  atomic  = true
#  wait    = true
#  timeout = 900
#
#  cleanup_on_fail = true
#
#  dependency_update = true
#  force_update = true
#}
