apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - external-secrets-namespace.yaml
    - external-secrets-repositories.yaml
    - external-secrets-crds.yaml
    - external-secrets-deployment.yaml
    - external-secrets-crs.yaml
