---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: crossplane-aws
    namespace: flux-system
spec:
    interval: 1m
    path: ./applications/crossplane/aws
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
