# How to manage values files. Ref: https://fluxcd.io/docs/guides/helmreleases/#refer-to-values-inside-the-chart
# How to inject values: https://fluxcd.io/docs/guides/helmreleases/#cloud-storage
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: istiod
    namespace: istio-system
spec:
    releaseName: istiod
    targetNamespace: istio-system
    interval: 1m
    dependsOn:
        - name: istio-base
          namespace: istio-system
    chart:
        spec:
            chart: istiod
            sourceRef:
                kind: HelmRepository
                name: istio
                namespace: istio-system
    values:
        defaults:
            meshConfig:
                enableTracing: true
                accessLogFile: /dev/stdout
                defaultConfig:
                    tracingServiceName: APP_LABEL_AND_NAMESPACE
                    tracing:
                        zipkin:
                            sampling: 100.0

            global:
                proxy:
                    logLevel: info
    # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install
    install:
        crds: Create
        createNamespace: true
