# How to manage values files. Ref: https://fluxcd.io/docs/guides/helmreleases/#refer-to-values-inside-the-chart
# How to inject values: https://fluxcd.io/docs/guides/helmreleases/#cloud-storage
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: istio-ingressgateway
    namespace: istio-system
spec:
    releaseName: istio-ingressgateway
    targetNamespace: istio-system
    interval: 1m
    dependsOn:
        - name: istiod
          namespace: istio-system
    chart:
        spec:
            chart: gateway
            sourceRef:
                kind: HelmRepository
                name: istio
                namespace: istio-system
    # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install
    install:
        disableWait: true
        crds: Create
        createNamespace: true
#---
#apiVersion: helm.toolkit.fluxcd.io/v2
#kind: HelmRelease
#metadata:
#    name: istio-egressgateway
#    namespace: istio-system
#spec:
#    releaseName: istio-egressgateway
#    targetNamespace: istio-system
#    interval: 1m
#    dependsOn:
#        - name: istiod
#          namespace: istio-system
#    chart:
#        spec:
#            chart: gateway
#            sourceRef:
#                kind: HelmRepository
#                name: istio
#                namespace: istio-system
#    # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install
#    install:
#        disableWait: true
#        crds: Create
#        createNamespace: true
