apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - prometheus.yaml
    - grafana.yaml
    - gateway.yaml
    - repositories.yaml
    - istio-base.yaml
    - istiod.yaml
    - istio-gateway.yaml
    - jaeger.yaml
    - loki.yaml
    - prometheus-operator.yaml
