---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: prometheus
    namespace: flux-system
spec:
    releaseName: kube-prometheus-stack
    targetNamespace: prometheus
    interval: 1m
    chart:
        spec:
            chart: kube-prometheus-stack
            version: "58.5.1"
            sourceRef:
                kind: HelmRepository
                name: prometheus
                namespace: flux-system
    install:
        crds: Create
        createNamespace: true
