---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
    name: management-cluster-control-plane-iam-role-policy-attachment-eks-cluster
spec:
    forProvider:
        policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

        roleRef:
            name: management-cluster-control-plane-iam-role
