---
apiVersion: eks.aws.upbound.io/v1beta1
kind: Addon
metadata:
    name: management-cluster-addon-amazon-cloudwatch-observability
spec: # aws eks describe-addon-versions --kubernetes-version 1.29 --addon-name amazon-cloudwatch-observability --query 'addons[].addonVersions[].{Version: addonVersion, Defaultversion: compatibilities[0].defaultVersion}' --output table
    forProvider:
        region: us-east-2

        addonName: "amazon-cloudwatch-observability"
        clusterNameRef:
            name: management-cluster
        addonVersion: "v1.6.0-eksbuild.1"
        resolveConflictsOnCreate: "OVERWRITE"
        resolveConflictsOnUpdate: "OVERWRITE"

        tags:
            Name: "amazon-cloudwatch-observability"
