---
apiVersion: eks.aws.upbound.io/v1beta1
kind: Addon
metadata:
    name: management-cluster-addon-aws-ebs-csi-driver
spec: # aws eks describe-addon-versions --kubernetes-version 1.29 --addon-name aws-ebs-csi-driver --query 'addons[].addonVersions[].{Version: addonVersion, Defaultversion: compatibilities[0].defaultVersion}' --output table
    forProvider:
        region: us-east-2

        addonName: "aws-ebs-csi-driver"
        clusterNameRef:
            name: management-cluster
        addonVersion: "v1.30.0-eksbuild.1"
        resolveConflictsOnCreate: "OVERWRITE"
        resolveConflictsOnUpdate: "OVERWRITE"

        tags:
            Name: "aws-ebs-csi-driver"
