---
apiVersion: eks.aws.upbound.io/v1beta1
kind: Addon
metadata:
    name: management-cluster-addon-eks-pod-identity-agent
spec: # aws eks describe-addon-versions --kubernetes-version 1.29 --addon-name eks-pod-identity-agent --query 'addons[].addonVersions[].{Version: addonVersion, Defaultversion: compatibilities[0].defaultVersion}' --output table
    forProvider:
        region: us-east-2

        addonName: "eks-pod-identity-agent"
        clusterNameRef:
            name: management-cluster
        addonVersion: "v1.2.0-eksbuild.1"
        resolveConflictsOnCreate: "OVERWRITE"
        resolveConflictsOnUpdate: "OVERWRITE"

        tags:
            Name: "eks-pod-identity-agent"
