---
apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
    name: management-cluster
spec:
    forProvider:
        region: us-east-2

        version: "1.29"
        enabledClusterLogTypes: [ "audit", "api", "authenticator", "controllerManager", "scheduler" ]

        kubernetesNetworkConfig:
            -   ipFamily: ipv4

        vpcConfig:
            -   endpointPrivateAccess: true
                endpointPublicAccess: true
                securityGroupIdRefs:
                    -   name: management-cluster-control-plane-security-group
                subnetIdRefs:
                    -   name: primary-workload-subnet-public-1
                    -   name: primary-workload-subnet-public-2
                    -   name: primary-workload-subnet-public-3

        roleArnRef:
            name: management-cluster-control-plane-iam-role

        tags:
            Name: Management-Cluster
