apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - security-group.yaml
    - security-group-rule-egress.yaml
    - security-group-rule-ingress.yaml

    - cluster-iam-role.yaml
    - cluster-iam-role-policy-attachment-eks-cluster.yaml
    - cluster-iam-role-policy-attachment-eks-vpc-resource-controller.yaml

    - kubernetes-cluster.yaml
