apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - security-group.yaml
    - security-group-rule-egress.yaml
    - security-group-rule-ingress.yaml

    - cluster-iam-role.yaml
    - cluster-iam-role-policy-attachment-eks-cluster.yaml
    - cluster-iam-role-policy-attachment-eks-vpc-resource-controller.yaml

    # - eks-cluster.yaml

    # - eks-cluster-addon-amazon-cloudwatch-observability.yaml
    # - eks-cluster-addon-aws-ebs-csi-driver.yaml
    # - eks-cluster-addon-coredns.yaml
    # - eks-cluster-addon-eks-pod-identity-agent.yaml
    # - eks-cluster-addon-kube-proxy.yaml
    # - eks-cluster-addon-vpc-cni.yaml
