---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
    name: management-cluster-control-plane-security-group
spec:
    forProvider:
        region: us-east-2

        name: Management-Cluster-Control-Plane-Security-Group
        description: Primary Security Group for Management Cluster Control Plane

        vpcIdRef:
            name: primary-workload-vpc

        tags:
            Name: Management-Cluster-Control-Plane-Security-Group
