---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: aws-crossplane-provider-credentials
    namespace: flux-system
spec:
    secretStoreRef:
        name: aws-cluster-secret-store-provider
        kind: ClusterSecretStore

    # RefreshInterval is the amount of time before the values reading again from the SecretStore provider
    # Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h" (from time.ParseDuration)
    # May be set to zero to fetch and create it once
    refreshInterval: "0"

    # the target describes the secret that shall be created
    # there can only be one target per ExternalSecret
    target:
        # The secret name of the resource
        # Defaults to .metadata.name of the ExternalSecret
        # It is immutable
        # name: application-config

        # Enum with values: 'Owner', 'Merge', or 'None'
        # Default value of 'Owner'
        # Owner creates the secret and sets .metadata.ownerReferences of the resource
        # Merge does not create the secret, but merges in the data fields to the secret
        # None does not create a secret (future use with injector)
        creationPolicy: Owner

        # DeletionPolicy defines how/when to delete the Secret in Kubernetes
        # if the provider secret gets deleted.
        # Valid values are Delete, Merge, Retain
        deletionPolicy: Delete

        # Specify a blueprint for the resulting Kind=Secret
        template:
            engineVersion: v2
            type: "Opaque"
            data:
                profile: "{{ . }}"
            #data: |
            #    [default]
            #    aws_access_key_id={{ index . \"aws-access-key-id\" }}
            #    aws_secret_access_key={{ index . \"aws-secret-access-key\" }}

    # Data defines the connection between the Kubernetes Secret keys and the Provider data
    dataFrom:
        -   extract:
                key: "local/crossplane/provider/aws/credentials"
                version: AWSCURRENT
                decodingStrategy: None
