apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
    name: aws-cluster-secret-store-provider
    labels:
        provider: aws
        dependency.namespace.secret.k8s.io: flux-system
        dependency.name.secret.k8s.io: aws-external-secrets-provider
spec:
    provider:
        aws:
            region: us-east-2
            service: SecretsManager
            secretsManager:
                forceDeleteWithoutRecovery: true
            auth:
                secretRef:
                    accessKeyIDSecretRef:
                        namespace: flux-system
                        name: aws-external-secrets-provider
                        key: aws-access-key-id
                    secretAccessKeySecretRef:
                        namespace: flux-system
                        name: aws-external-secrets-provider
                        key: aws-secret-access-key
