apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
    name: aws-cluster-secret-store
spec:
    provider:
        aws:
            region: us-east-2
            service: SecretsManager
            secretsManager:
                forceDeleteWithoutRecovery: true
            auth:
                secretRef:
                    accessKeyIDSecretRef:
                        namespace: flux-system
                        name: aws-external-secrets-credentials
                        key: aws-access-key-id
                    secretAccessKeySecretRef:
                        namespace: flux-system
                        name: aws-external-secrets-credentials
                        key: aws-secret-access-key
