---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
    name: primary-workload-subnet-caching-2
spec:
    forProvider:
        region: us-east-2

        availabilityZone: "us-east-2b"
        cidrBlock: "10.0.160.0/20"
        enableDns64: false
        enableResourceNameDnsARecordOnLaunch: true
        mapPublicIpOnLaunch: false

        vpcIdRef:
            name: primary-workload-vpc

        tags:
            Name: Primary-Management-Caching-Subnet-2
