---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
    name: primary-workload-subnet-public-3
spec:
    forProvider:
        region: us-east-2

        availabilityZone: "us-east-2c"
        cidrBlock: "10.0.80.0/20"
        enableDns64: false
        enableResourceNameDnsARecordOnLaunch: true
        mapPublicIpOnLaunch: true

        vpcIdRef:
            name: primary-workload-vpc

        tags:
            Name: Primary-Management-Public-Subnet-3
