---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
    name: primary-workload-subnet-public-1
spec:
    forProvider:
        region: us-east-2

        availabilityZone: "us-east-2a"
        cidrBlock: "10.0.48.0/20"
        enableDns64: false
        enableResourceNameDnsARecordOnLaunch: true
        mapPublicIpOnLaunch: true

        vpcIdRef:
            name: primary-workload-vpc

        tags:
            Name: Primary-Management-Public-Subnet-1
