#  "10.0.48.0/20",
#  "10.0.64.0/20",
#  "10.0.80.0/20",

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
    name: primary-workload-subnet-public-1
    labels:
        ethr.gg/exported-resource-selector: primary-workload-subnet-public-1
spec:
    forProvider:
        region: us-east-2

        availabilityZone: "us-east-2a"
        cidrBlock: "10.0.48.0/20"
        enableDns64: false
        enableResourceNameDnsARecordOnLaunch: true
        mapPublicIpOnLaunch: true

        vpcIdRef:
            name: primary-workload-vpc

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
    name: primary-workload-subnet-public-2
    labels:
        ethr.gg/exported-resource-selector: primary-workload-subnet-public-2
spec:
    forProvider:
        region: us-east-2

        availabilityZone: "us-east-2b"
        cidrBlock: "10.0.64.0/20"
        enableDns64: false
        enableResourceNameDnsARecordOnLaunch: true
        mapPublicIpOnLaunch: true

        vpcIdRef:
            name: primary-workload-vpc

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
    name: primary-workload-subnet-public-3
    labels:
        ethr.gg/exported-resource-selector: primary-workload-subnet-public-3
spec:
    forProvider:
        region: us-east-2

        availabilityZone: "us-east-2c"
        cidrBlock: "10.0.80.0/20"
        enableDns64: false
        enableResourceNameDnsARecordOnLaunch: true
        mapPublicIpOnLaunch: true

        vpcIdRef:
            name: primary-workload-vpc
