#  "10.0.0.0/20",
#  "10.0.16.0/20",
#  "10.0.32.0/20",

#  "10.0.48.0/20",
#  "10.0.64.0/20",
#  "10.0.80.0/20",

#  "10.0.96.0/20",
#  "10.0.112.0/20",
#  "10.0.128.0/20",

#  "10.0.144.0/20",
#  "10.0.160.0/20",
#  "10.0.176.0/20",
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
    name: primary-workload-vpc
    labels:
        ethr.gg/exported-resource-selector: primary-workload-vpc
spec:
    forProvider:
        region: us-east-2

        cidrBlock: 10.0.0.0/16
        enableDnsHostnames: true
        enableDnsSupport: true
        enableNetworkAddressUsageMetrics: false
        assignGeneratedIpv6CidrBlock: true
