# How to manage values files. Ref: https://fluxcd.io/docs/guides/helmreleases/#refer-to-values-inside-the-chart
# How to inject values: https://fluxcd.io/docs/guides/helmreleases/#cloud-storage
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cert-manager
    namespace: flux-system
spec:
    releaseName: cert-manager
    targetNamespace: cert-manager
    interval: 1m
    chart:
        spec:
            chart: cert-manager
            version: 1.14.5
            sourceRef:
                kind: HelmRepository
                name: cert-manager
                namespace: flux-system
    values:
        installCRDs: true
    # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install
    install:
        crds: Create
        createNamespace: true
