---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: external-secrets
    namespace: flux-system
spec:
    interval: 1m
    path: ./applications/external-secrets
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    name: external-secrets
    namespace: flux-system
spec:
    interval: 1m
    ref:
        branch: main
    url: http://github.com/external-secrets/external-secrets
