---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: istio
    namespace: flux-system
spec:
    dependsOn:
        -   name: kiali
            namespace: flux-system
    interval: 1m
    path: ./applications/istio
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
