---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: kiali
    namespace: flux-system
spec:
    dependsOn:
        -   name: istio
            namespace: flux-system
        -   name: jaeger
            namespace: flux-system
        -   name: prometheus
            namespace: flux-system
    interval: 1m
    path: ./applications/kiali
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
