---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: kyverno-policies:external-secrets
    labels:
        app.kubernetes.io/component: background-controller
        app.kubernetes.io/instance: kyverno
        app.kubernetes.io/part-of: kyverno
rules:
    -   apiGroups:
            - external-secrets.io
        resources:
            - externalsecrets
        verbs:
            - create
            - update
            - delete
