---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: kyverno
    namespace: kyverno
spec:
    interval: 1m
    url: https://kyverno.github.io/kyverno
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    name: kyverno
    namespace: kyverno
spec:
    interval: 1m
    ref:
        branch: main
    url: https://github.com/kyverno/kyverno
